name: CI

# Events that trigger the workflow
on:
  # Runs on all pushes to branches
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  # Runs on all PRs
  pull_request:
  # Manual Dispatch
  workflow_dispatch:

concurrency:
  # Behavior:
  # - Group all pull requests: latest push cancels previous ones
  # - Group all branches:
  #   - If main/version- branches: run serially
  #   - Else, latest push cancels previous ones
  group: >
    ${{
      (github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number)) ||
      (github.event_name == 'push' && format('branch-{0}', github.ref_name)) ||
      ''
    }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || !(startsWith(github.ref_name, 'version-') || github.ref_name == 'main' || github.ref_name == 'dev') }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Define the Matrix
        id: export-matrix
        if: 
        run: |
          if ${{ github.repository == 'wafer-space/gf180mcu-project-template' }}; then
            echo "matrix={\"slot\":['1x1', '0p5x1', '1x0p5', '0p5x0p5'],\"domain\":['5v','3v3'],\"include\": [{\"pad\": 'gf180mcu_fd_io', \"domain\": '5v'},{\"scl\": 'gf180mcu_fd_sc_mcu7t5v0', \"domain\": '5v'},{\"sram\": 'gf180mcu_fd_ip_sram', \"domain\": '5v'},{\"pad\": 'gf180mcu_ocd_io', \"domain\": '3v3'},{\"scl\": 'gf180mcu_as_sc_mcu7t3v3', \"domain\": '3v3'},{\"sram\": 'gf180mcu_ocd_ip_sram', \"domain\": '3v3'}]}" >> $GITHUB_OUTPUT
          else
            echo "matrix={\"slot\":['default'],\"domain\":['default'],\"sram\":['default'],\"pad\":['default'],\"scl\":['default']}" >> $GITHUB_OUTPUT
          fi
    outputs:
      matrix: ${{ steps.export-matrix.outputs.matrix }}
  chip:
    runs-on: ubuntu-24.04
    name: Build the Chip
    needs:
      - prepare
    strategy:
      matrix: ${{fromJSON(needs.prepare.outputs.matrix)}}
    steps:
      - name: Set variables
        run: |
          echo "SLOT=${{ matrix.slot }}" >> $GITHUB_ENV
          echo "SRAM=${{ matrix.sram }}" >> $GITHUB_ENV
          echo "PAD=${{ matrix.pad }}" >> $GITHUB_ENV
          echo "SCL=${{ matrix.scl }}" >> $GITHUB_ENV
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
      - uses: actions/checkout@v6
      - name: Setup Nix
        uses: ./.github/actions/setup_nix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          nix_cache_domain: ${{ vars.NIX_CACHE }}
          nix_public_key: ${{ vars.NIX_PUBLIC_KEY }}
      - name: Build with Nix
        uses: ./.github/actions/build_nix
        with:
          nix_system: x86_64-linux
      - name: Check Nix
        run: |
          sudo du -hs /nix/store/* | sort -h | tail -n 10
          sudo tree /nix/store/*-librelane || true
      - name: Clone the PDK
        run: |
          nix develop --command make clone-pdk
      - name: Run RTL simulation
        run: |
          nix develop --command make sim
          # cocotb also returns 0 upon failure
          # check the simulation results
          ! grep failure cocotb/sim_build/results.xml
      - name: Implement the Chip
        if: success() || failure()
        run: |
          nix develop --command make librelane-condensed
      - name: Create summary
        if: success() || failure()
        run: |
          echo "# Manufacturability" >> $GITHUB_STEP_SUMMARY
          cat librelane/runs/*/*-misc-reportmanufacturability/manufacturability.rpt >> $GITHUB_STEP_SUMMARY
      - name: Print the hash
        if: success() || failure()
        run: |
          shasum final/gds/*
      - name: Upload GDS
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.slot }}_${{ matrix.domain }}_gds
          path: final/gds/*
      - name: Upload image
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.slot }}_${{ matrix.domain }}_image
          path: final/render/*.png
      - name: Run GL simulation
        if: success() || failure()
        run: |
          nix develop --command make sim-gl
          # cocotb also returns 0 upon failure
          # check the simulation results
          ! grep failure cocotb/sim_build/results.xml
